version: '2'
exclude_patterns:
  - 'database/'
plugins:
  eslint:
    enabled: true
    channel: 'eslint-5'
    config:
      config: './eslintrc.json'
  duplication:
    enabled: true
    config:
      languages:
        js:
          checks:
            identical-code:
              config:
                threshold: 25
            similar-code:
              config:
                threshold: 50
            method-lines:
              config:
                threshold: 50

