version: 2
defaults: &defaults
  machine:
    environment:
      # Add the Postgres 9.6 binaries to the path.
      PATH: /usr/lib/postgresql/9.6/bin/:$PATH
    pre:
      # Start Postgres 9.6.
      - sudo service postgresql start 9.6

      # Create a new test database.
      - sudo -u postgres psql -p 5432 -c "create database events_test_db;"
    docker:
      - image: circleci/node:11.8.0
        environment:
          DATABASE: events_test_db
          DATABASE_USER: root
          HOST: localhost
      - image: circleci/postgres:9.6
        environment:
          POSTGRES_DB: events_test_db
          POSTGRES_USER: root
jobs:
  build:
    <<: *defaults
    steps:
      - run:
          name: Download cc-test-reporter
          command: |
            mkdir -p tmp/
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./tmp/cc-test-reporter
            chmod +x ./tmp/cc-test-reporter
      - persist_to_workspace:
          root: tmp
          paths:
            - cc-test-reporter
  app-tests:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn
      - restore_cache: # special step to restore the dependency cache
          key: dependency-cache-{{checksum "package.json"}}
      - save_cache: # saving cache for faster restoration
          key: dependency-cache-{{checksum "package.json"}}
          paths:
            - ./node_modules
      - run:
          name: Run tests
          command: yarn test
  upload-coverage:
    <<: *defaults
    environment:
      - CC_TEST_REPORTER_ID: 3bfb0b50c49cf35857fa0f1196ba56b00d4cb7c9aab8a1d5b855002f3c3a3bdc
    steps:
      - attach_workspace:
          at: ~/repo/tmp
      - run:
          name: Upload coverage results to Code Climate
          command: |
            ./tmp/cc-test-reporter sum-coverage tmp/codeclimate.*.json -p 2 -o tmp/codeclimate.total.json
            ./tmp/cc-test-reporter upload-coverage -i tmp/codeclimate.total.json
