version: 2
orbs:
  codecov: codecov/codecov@1.0.2
defaults: &defaults
  machine:
    environment:
      # Add the Postgres 9.6 binaries to the path.
      PATH: /usr/lib/postgresql/9.6/bin/:$PATH
    pre:
      # Start Postgres 9.6.
      - sudo service postgresql start 9.6

      # Create a new test database.
      - sudo -u postgres psql -p 5432 -c "create database sb-events-test;"
    docker:
      - image: circleci/node:11.8.0
        environment:
          DATABASE: sb-events-test
          DATABASE_USER: root
          HOST: localhost
      - image: circleci/postgres:9.6
        environment:
          POSTGRES_DB: sb-events-test
          POSTGRES_USER: root
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn
      - restore_cache: # special step to restore the dependency cache
          key: dependency-cache-{{checksum "package.json"}}
      - save_cache: # saving cache for faster restoration
          key: dependency-cache-{{checksum "package.json"}}
          paths:
            - ./node_modules
      - run:
          name: Download cc-test-reporter
          command: |
            mkdir -p tmp/
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./tmp/cc-test-reporter
            chmod +x ./tmp/cc-test-reporter
      - run:
          name: Run tests
          command: yarn test
      - persist_to_workspace:
          root: tmp
          paths:
            - cc-test-reporter
