version: 2
orbs:
  codecov: codecov/codecov@1.0.2
defaults: &defaults
  machine:
    environment:
      # Add the Postgres 9.6 binaries to the path.
      PATH: /usr/lib/postgresql/9.6/bin/:$PATH
    pre:
      # Start Postgres 9.6.
      - sudo service postgresql start 9.6

      # Create a new test database.
      - sudo -u postgres psql -p 5432 -c "create database events_test_db;"
    docker:
      - image: circleci/node:11.8.0
        environment:
          DATABASE: events_test_db
          DATABASE_USER: root
          HOST: localhost
      - image: circleci/postgres:9.6
        environment:
          POSTGRES_DB: events_test_db
          POSTGRES_USER: root
jobs:
  build:
  environment:
      CC_TEST_REPORTER_ID: 61f35672cf2dfc9d3171b614ea08d18f72ce23549d31d1a20dd2a7471a665ec7
    <<: *defaults
    steps:
      - run:
          name: Download cc-test-reporter
          command: |
            mkdir -p tmp/
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./tmp/cc-test-reporter
            chmod +x ./tmp/cc-test-reporter
      - persist_to_workspace:
          root: tmp
          paths:
            - cc-test-reporter
  app-tests:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn
      - restore_cache: # special step to restore the dependency cache
          key: dependency-cache-{{checksum "package.json"}}
      - save_cache: # saving cache for faster restoration
          key: dependency-cache-{{checksum "package.json"}}
          paths:
            - ./node_modules
      - run:
          name: Run tests
          command: |
            ./cc-test-reporter before-build
            yarn test
            ./cc-test-reporter after-build --coverage-input-type lcov --exit-code $?
